// <auto-generated />
using System;
using MVC.Study._01.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Study._01.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Study._01.Context.Concrete.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");

                    b.HasData(
                        new
                        {
                            MusteriId = 1,
                            Ad = "Ali",
                            Email = "ali.yilmaz@example.com",
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            MusteriId = 2,
                            Ad = "Ayşe",
                            Email = "ayse.kara@example.com",
                            Soyad = "Kara"
                        },
                        new
                        {
                            MusteriId = 3,
                            Ad = "Mehmet",
                            Email = "mehmet.demir@example.com",
                            Soyad = "Demir"
                        },
                        new
                        {
                            MusteriId = 4,
                            Ad = "Fatma",
                            Email = "fatma.ozturk@example.com",
                            Soyad = "Öztürk"
                        },
                        new
                        {
                            MusteriId = 5,
                            Ad = "Hasan",
                            Email = "hasan.celik@example.com",
                            Soyad = "Çelik"
                        },
                        new
                        {
                            MusteriId = 6,
                            Ad = "Zeynep",
                            Email = "zeynep.koc@example.com",
                            Soyad = "Koç"
                        },
                        new
                        {
                            MusteriId = 7,
                            Ad = "Emre",
                            Email = "emre.aydin@example.com",
                            Soyad = "Aydın"
                        },
                        new
                        {
                            MusteriId = 8,
                            Ad = "Seda",
                            Email = "seda.akman@example.com",
                            Soyad = "Akman"
                        },
                        new
                        {
                            MusteriId = 9,
                            Ad = "Burak",
                            Email = "burak.sonmez@example.com",
                            Soyad = "Sönmez"
                        },
                        new
                        {
                            MusteriId = 10,
                            Ad = "Elif",
                            Email = "elif.yavuz@example.com",
                            Soyad = "Yavuz"
                        });
                });

            modelBuilder.Entity("MVC.Study._01.Context.Concrete.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SiparisId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("UrunId");

                    b.ToTable("Siparisler");

                    b.HasData(
                        new
                        {
                            SiparisId = 1,
                            MusteriId = 1,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8406),
                            UrunId = 1
                        },
                        new
                        {
                            SiparisId = 2,
                            MusteriId = 1,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8416),
                            UrunId = 2
                        },
                        new
                        {
                            SiparisId = 3,
                            MusteriId = 2,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8418),
                            UrunId = 3
                        },
                        new
                        {
                            SiparisId = 4,
                            MusteriId = 2,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8419),
                            UrunId = 4
                        },
                        new
                        {
                            SiparisId = 5,
                            MusteriId = 3,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8420),
                            UrunId = 5
                        },
                        new
                        {
                            SiparisId = 6,
                            MusteriId = 3,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8422),
                            UrunId = 6
                        },
                        new
                        {
                            SiparisId = 7,
                            MusteriId = 4,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8423),
                            UrunId = 7
                        },
                        new
                        {
                            SiparisId = 8,
                            MusteriId = 5,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8424),
                            UrunId = 8
                        },
                        new
                        {
                            SiparisId = 9,
                            MusteriId = 6,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8425),
                            UrunId = 9
                        },
                        new
                        {
                            SiparisId = 10,
                            MusteriId = 7,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8427),
                            UrunId = 10
                        },
                        new
                        {
                            SiparisId = 11,
                            MusteriId = 8,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8428),
                            UrunId = 1
                        },
                        new
                        {
                            SiparisId = 12,
                            MusteriId = 9,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8429),
                            UrunId = 2
                        },
                        new
                        {
                            SiparisId = 13,
                            MusteriId = 10,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8430),
                            UrunId = 3
                        },
                        new
                        {
                            SiparisId = 14,
                            MusteriId = 4,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8431),
                            UrunId = 5
                        },
                        new
                        {
                            SiparisId = 15,
                            MusteriId = 5,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8432),
                            UrunId = 6
                        },
                        new
                        {
                            SiparisId = 16,
                            MusteriId = 6,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8434),
                            UrunId = 7
                        },
                        new
                        {
                            SiparisId = 17,
                            MusteriId = 7,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8435),
                            UrunId = 8
                        },
                        new
                        {
                            SiparisId = 18,
                            MusteriId = 8,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8436),
                            UrunId = 9
                        },
                        new
                        {
                            SiparisId = 19,
                            MusteriId = 9,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8437),
                            UrunId = 10
                        },
                        new
                        {
                            SiparisId = 20,
                            MusteriId = 10,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 43, 28, 424, DateTimeKind.Local).AddTicks(8438),
                            UrunId = 1
                        });
                });

            modelBuilder.Entity("MVC.Study._01.Context.Concrete.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunId = 1,
                            Fiyat = 2500m,
                            UrunAdi = "Laptop"
                        },
                        new
                        {
                            UrunId = 2,
                            Fiyat = 1500m,
                            UrunAdi = "Akıllı Telefon"
                        },
                        new
                        {
                            UrunId = 3,
                            Fiyat = 1200m,
                            UrunAdi = "Tablet"
                        },
                        new
                        {
                            UrunId = 4,
                            Fiyat = 300m,
                            UrunAdi = "Kulaklık"
                        },
                        new
                        {
                            UrunId = 5,
                            Fiyat = 2000m,
                            UrunAdi = "Masaüstü Bilgisayar"
                        },
                        new
                        {
                            UrunId = 6,
                            Fiyat = 800m,
                            UrunAdi = "Monitör"
                        },
                        new
                        {
                            UrunId = 7,
                            Fiyat = 400m,
                            UrunAdi = "Klavyeli"
                        },
                        new
                        {
                            UrunId = 8,
                            Fiyat = 600m,
                            UrunAdi = "Yazıcı"
                        },
                        new
                        {
                            UrunId = 9,
                            Fiyat = 250m,
                            UrunAdi = "Modem"
                        },
                        new
                        {
                            UrunId = 10,
                            Fiyat = 500m,
                            UrunAdi = "Harici Disk"
                        });
                });

            modelBuilder.Entity("MVC.Study._01.Context.Concrete.Siparis", b =>
                {
                    b.HasOne("MVC.Study._01.Context.Concrete.Musteri", "Musteri")
                        .WithMany("Siparisler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC.Study._01.Context.Concrete.Urun", "Urun")
                        .WithMany("Siparisler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MVC.Study._01.Context.Concrete.Musteri", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("MVC.Study._01.Context.Concrete.Urun", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
